[[results]]
probe = "custom-timers"
exit-code = 0
stdout = '''
maintenance-reboot.timer    { OnCalendar=Sun *-*-* 04:30:00 ; next_elapse=Sun 2026-10-04 04:30:00 CEST }
restic-backup.timer         { OnCalendar=*-*-* 03:00:00 ; next_elapse=Sun 2026-10-04 03:00:00 CEST }
restic-check.timer          { OnCalendar=Sun *-*-* 05:00:00 ; next_elapse=Sun 2026-10-04 05:00:00 CEST }
restic-offsite.timer        { OnCalendar=Sun *-*-* 06:00:00 ; next_elapse=Sun 2026-10-04 06:00:00 CEST }
'''

[[results]]
probe = "offsite-last-run"
exit-code = 0
stdout = '''
ExecMainStartTimestamp=Sun 2026-09-27 06:00:02 CEST
Result=success
'''
