[[results]]
probe = "custom-timers"
exit-code = 0
stdout = '''
maintenance-reboot.timer    { OnCalendar=Sun *-*-* 04:30:00 ; next_elapse=Sun 2026-10-04 04:30:00 CEST }
restic-backup.timer         { OnCalendar=*-*-* 03:00:00 ; next_elapse=Sun 2026-10-04 03:00:00 CEST }
restic-check.timer          { OnCalendar=Sun *-*-* 05:00:00 ; next_elapse=Sun 2026-10-04 05:00:00 CEST }
'''

[[results]]
probe = "cron-d"
exit-code = 0
stdout = '''
== /etc/cron.d/timeshift-boot
@reboot root sleep 10m && timeshift --create --scripted --tags B
== /etc/cron.d/timeshift-hourly
0 9-21 * * * root timeshift --check --scripted
'''

[[results]]
probe = "restic-version"
exit-code = 0
stdout = '''
restic 0.18.1 compiled with go1.25.1 on linux/amd64
'''

[[results]]
probe = "cloud-status"
exit-code = 0
stdout = '''
200 application/json; charset=utf-8
'''
